### ISSUE TITLE
clarify relation between scouty and one-t

### ISSUE THREAD

**Issue by nicolasochem** [turboflakes/scouty#1]
Hi, thank you for the great work.

Looking at the repos, I don't understand how scouty and one-t interact with one another.

If I run scouty on my server and set up a matrix user, will I get the same kind of statistics than one-t?

**Comment by paulormart** [comment]
No. They are different bots with a different purpose and completely independent. 

Scouty born out of a necessity to listen to some particular on-chain events and receive the respective notifications. But with the particularity that you could hook a _script_ to that event to trigger whatever you would like to be executed when that event occurs.

ONE-T just came out recently with the necessity of showing up a general stats about the state of Polkadot and Kusama network, what's the impact of TVP validators on the network.. etc. And goes a bit in detail on how a validator is performing against their peers while para-validating.
